// Full descriptions for all 64 gates — original writing, researched and
// cross-checked against standard Human Design reference sources for each
// gate's traditional theme (see PDF report validation notes in README.md).
export const GATE_DESCRIPTIONS = {
  17: "Gate 17 (Following) generates opinions built from noticing patterns and drawing logical conclusions about what will likely happen next. It gives a talent for organizing scattered facts into a clear, confidently stated position. The catch is timing: these views land well when someone has actually asked for them, and land as unsolicited lecturing when they haven't. At its best this is trustworthy analysis offered in service of others; unchecked, it becomes an attachment to being right.",
  18: "Gate 18 (Correction) is an instinctive radar for what's broken, inefficient, or out of alignment in a system, habit, or pattern — the impulse to spot the flaw and fix it. Done well, this is quiet, useful critique that improves whatever it touches. Under pressure, fueled by an underlying fear of not being good enough, it can tip into chronic fault-finding or perfectionism, criticizing everything rather than repairing anything in particular.",
  19: "Gate 19 (Approach) is a sensitivity to need — reading what a person, group, or situation requires before it's been asked for, whether that's material resources, closeness, or a sense of belonging. It drives the impulse to reach toward others and secure what's necessary for connection and survival. At its best it builds genuine interdependence; out of balance it can turn into anxious neediness or overextending to be included.",
  20: "Gate 20 (The Now) is the voice of pure presence — speaking, acting, or noticing directly from what's happening in this instant rather than from memory or plan. It carries a capacity to simply be with what's in front of it without immediately needing to analyze or change it. Under pressure this can become restless chatter or anxious self-monitoring about whether one is present enough, instead of genuine, grounded immediacy.",
  21: "Gate 21 (Control) carries the drive to manage resources, situations, and people directly — stepping in to take charge when something needs handling rather than waiting for consensus. It's a willful, protective energy aimed at securing what a family, team, or group needs to function. Well-placed, it's decisive, responsible leadership; misapplied, it turns into domineering control, micromanaging others, or fighting for authority that isn't actually needed.",
  22: "Gate 22 (Openness) is social and emotional grace — a warmth that can draw people in, put them at ease, and make space for real connection, but only when the underlying emotional mood allows it. Because it runs on the Solar Plexus wave, this openness isn't constant; it rises and recedes with feeling. At its best it's genuine, moved presence with others; at its worst, charm performed while emotionally checked out.",
  23: "Gate 23 (Assimilation) is the ability to take a complicated or unconventional idea and cut it down to the few words that actually land — breaking apart old assumptions to say something genuinely new. It favors truth over consensus, which can make its insights land as strange or premature to people not ready for them. At its best it's precise, original communication; at its worst, blunt statements delivered with no regard for how they're received.",
  24: "Gate 24 (Rationalization) is the mental habit of circling back to the same question or problem repeatedly, turning it over until a flash of insight finally makes sense in words. It's less about the first thought and more about the returns — refining a realization each time it's revisited until it becomes something explainable. At its best this produces real clarity from persistence; under pressure it can loop into repetitive, addictive rumination that never actually lands.",
  25: "Gate 25 (Innocence) is a love that isn't earned or conditional — an underlying acceptance of life and of one's own experience exactly as it is, including the parts that hurt. It carries a spontaneous, uncalculated quality, acting from spirit rather than strategy. At its best this reads as genuine, undefended presence and universal regard for others; under strain, especially through illness or loss, that innocence can curdle into naivety or self-blame.",
  26: "Gate 26 (The Egoist) is the willpower to influence, persuade, and manage resources on behalf of a group — a natural salesperson's gift for shaping how others see a situation. It works by selective memory and framing, emphasizing what serves the larger goal. At its best this builds trust and provides real value through negotiation and care for others' needs; at its worst it slides into manipulation, exaggeration, or self-serving spin.",
  27: "Gate 27 (Caring) is the Sacral drive to nurture — feeding, protecting, and supporting others physically and emotionally as a matter of instinct. It's a generous, other-directed energy that shows up as caregiving, generosity, and concern for wellbeing. Its necessary balance is self-care: without also being nourished in return, the drive to care for others tips into depletion, overprotection, or an inability to set boundaries around what's given away.",
  28: "Gate 28 (The Game Player) carries a deep-seated awareness of mortality — the fear of reaching the end of life without having found what made it worth living. That pressure drives a willingness to take real risks and stay in difficult situations others would walk away from, in the search for meaning. Guided by spleen instinct about which risks are worth it, this becomes purposeful courage; unguided, it becomes recklessness for its own sake.",
  29: "Gate 29 (Perseverance) is the Sacral capacity to commit fully once a yes has been given, and to keep going through difficulty rather than abandoning something halfway. Its value isn't in the commitment itself but in what's discovered by staying the course through hardship. At its best this is deep, reliable follow-through; misapplied — saying yes to everything, or to the wrong things — it becomes overcommitment and exhausting, directionless effort.",
  30: "Gate 30 (Feelings) is the fire of desire — an emotional intensity that longs for new experience and a sense of a life fully lived. It generates cravings and fantasies that can feel urgent even before there's any real plan behind them. At its best, held with patience through the emotional wave, this desire becomes the fuel for meaningful experience; rushed or unchecked, it burns as restlessness, excess, or attachment to feelings that never satisfy.",
  31: "Gate 31 (Leading) is leadership through influence rather than authority — the capacity to speak in a way that others willingly follow because it represents what they already want. This is leadership that depends on being heard and endorsed by the group, not imposed on it. At its best it rallies people around a shared direction with real democratic legitimacy; at its worst it becomes empty rhetoric or leading without anyone actually choosing to follow.",
  32: "Gate 32 (Continuity) is an instinctive sense for what will actually endure — which ideas, plans, or efforts are built to survive the setbacks along the way and which will collapse under pressure. It brings a practical, conservative caution that protects against reckless failure. At its best this instinct preserves what's genuinely valuable while adapting it for the long run; driven by its underlying fear of failure, it can also curdle into excessive risk-aversion or resistance to change.",
};
