// The 64 gates: traditional name (adapted from the I Ching / King Wen
// sequence by Ra Uru Hu) and a short keynote theme. Purely descriptive
// content — standard and consistent across Human Design literature.
export const GATE_NAMES = {
  1: ["The Creative", "Self-Expression"],
  2: ["The Receptive", "The Direction of the Self"],
  3: ["Difficulty at the Beginning", "Ordering"],
  4: ["Youthful Folly", "Formulization"],
  5: ["Waiting", "Fixed Patterns"],
  6: ["Conflict", "Friction"],
  7: ["The Army", "The Role of the Self in Interaction"],
  8: ["Holding Together", "Contribution"],
  9: ["The Taming Power of the Small", "Focus"],
  10: ["Treading", "The Behavior of the Self"],
  11: ["Peace", "Ideas"],
  12: ["Standstill", "Caution"],
  13: ["The Fellowship of Man", "The Listener"],
  14: ["Possession in Great Measure", "Power Skills"],
  15: ["Modesty", "Extremes"],
  16: ["Enthusiasm", "Skills"],
  17: ["Following", "Opinions"],
  18: ["Work on What Has Been Spoiled", "Correction"],
  19: ["Approach", "Wanting"],
  20: ["Contemplation", "The Now"],
  21: ["Biting Through", "Control"],
  22: ["Grace", "Openness"],
  23: ["Splitting Apart", "Assimilation"],
  24: ["Return", "Rationalizing"],
  25: ["Innocence", "The Spirit of the Self"],
  26: ["The Taming Power of the Great", "The Egoist"],
  27: ["Nourishment", "Caring"],
  28: ["Preponderance of the Great", "The Game Player"],
  29: ["The Abysmal", "Perseverance"],
  30: ["The Clinging Fire", "Feelings"],
  31: ["Influence", "Leading"],
  32: ["Duration", "Continuity"],
  33: ["Retreat", "Privacy"],
  34: ["The Power of the Great", "Power"],
  35: ["Progress", "Change"],
  36: ["Darkening of the Light", "Crisis"],
  37: ["The Family", "Friendship"],
  38: ["Opposition", "The Fighter"],
  39: ["Obstruction", "Provocation"],
  40: ["Deliverance", "Aloneness"],
  41: ["Decrease", "Contraction"],
  42: ["Increase", "Growth"],
  43: ["Breakthrough", "Insight"],
  44: ["Coming to Meet", "Alertness"],
  45: ["Gathering Together", "The Gatherer"],
  46: ["Pushing Upward", "Determination"],
  47: ["Oppression", "Realization"],
  48: ["The Well", "Depth"],
  49: ["Revolution", "Principles"],
  50: ["The Cauldron", "Values"],
  51: ["The Arousing", "Shock"],
  52: ["Keeping Still", "Stillness"],
  53: ["Development", "Beginnings"],
  54: ["The Marrying Maiden", "Ambition"],
  55: ["Abundance", "Spirit"],
  56: ["The Wanderer", "Stimulation"],
  57: ["The Gentle", "Intuitive Clarity"],
  58: ["The Joyous", "Vitality"],
  59: ["Dispersion", "Sexuality"],
  60: ["Limitation", "Acceptance"],
  61: ["Inner Truth", "Mystery"],
  62: ["Preponderance of the Small", "Detail"],
  63: ["After Completion", "Doubt"],
  64: ["Before Completion", "Confusion"],
};
